# File generated by dynDeT

#XILINX_HOME=/opt/Xilinx
#XILINX_VERSION=2015.4
#BOOTGEN=$(XILINX_HOME)/SDK/$(XILINX_VERSION)/bin/bootgen
BOOTGEN=bootgen
BOARD_PART={{PART}}
BIT_PATH={{FULL_BITSTREAM}}
APP_PATH={{USER_APP}}


all: boot.bin

%.bin: %.bif bitstream.bit app.elf
	$(BOOTGEN) -p $(BOARD_PART) -image $< -o i $@

bitstream.bit:
	cp $(BIT_PATH) bitstream.bit

app.elf:
	cp $(APP_PATH) app.elf

clean:
	$(RM) *~ *.bit *.bin app.elf
