# File generated by dynDeT

PARTIAL_BITSTREAMS={{#PARTIAL_BITSTREAM}}{{PARTIAL_BITSTREAM_NAME}} {{/PARTIAL_BITSTREAM}}
BITSTREAMS_DIR={{BITSTREAMS_DIR}}

WRITE_TOOL_DIR=/usr/share/dynDeT/bin
WRITE_TOOL=$(WRITE_TOOL_DIR)/write_factory_bitstreams


all: build-partial-bitstreams program deploy

$(WRITE_TOOL):
	@cd $(WRITE_TOOL_DIR) ;\
	make; cd -

build-partial-bitstreams: $(WRITE_TOOL)
	@for i in $(PARTIAL_BITSTREAMS) ; do \
	  $(WRITE_TOOL) -z $(BITSTREAMS_DIR)$$i $(BITSTREAMS_DIR)/factory_$$i ;\
	done

read_mem: program
	xmd -tcl xmd_read.tcl

program: program.tcl
	vivado -mode batch -source $^
	
{{#VERSION_XMD}}
deploy: xmd.tcl
	xmd -tcl $^
{{/VERSION_XMD}}

{{#VERSION_XSDB}}
deploy: xsdb.tcl
	xsdb $^
{{/VERSION_XSDB}}

clean:
	$(RM) -rf $(BITSTREAMS_DIR)/factory_*

cleanall: clean
	@cd $(WRITE_TOOL_DIR) ;\
	make clean; cd -
