# File generated by dynDeT

source TCL/fileGroup.tcl
package require fileGroup 1.0

source TCL/rmGroup.tcl
package require rmGroup 1.0

source TCL/cfgGroup.tcl
package require cfgGroup 1.0

###############################################################
### Define Part, Package, Speedgrade 
###############################################################
set originDir ""
#set originDir [file dirname [info script]]
set part {{PART}}
set board "{{BOARD}}"
###############################################################


###############################################################
### Vivado Project
###############################################################
set blockDesign {{BLOCK_DESIGN_TCL}}
set designName "{{DESIGN_NAME}}"
set prjName {{PROJECT_NAME}}
set userIPDir {{USER_IP_DIR}}

set staticFiles [fileGroup::create]
{{#STATIC_FILE}}fileGroup::add $staticFiles {{STATIC_FILE_DIR}} {{STATIC_FILE_NAME}} {{#TOP_FILE}}"TRUE"{{/TOP_FILE}}
{{/STATIC_FILE}}

set constraintFiles [fileGroup::create]
{{#CONSTRAINT_FILE}}fileGroup::add $constraintFiles {{CONSTRAINT_FILE_DIR}} {{CONSTRAINT_FILE_NAME}}
{{/CONSTRAINT_FILE}}
###############################################################


###############################################################
### Reconfig Partitions
###############################################################
{{#RECONFIG_PARTITION}}# Create reconfig partition (RP)
set {{PARTITION_ID}} [rmGroup::create "{{PARTITION_NAME}}"]

# Configure RP
rmGroup::setSrcLocation ${{PARTITION_ID}} "{{PARTITION_SRC_DIR}}"
rmGroup::setInstanceName ${{PARTITION_ID}} "{{PARTITION_INSTANCE_NAME}}"
rmGroup::setHwResources ${{PARTITION_ID}} [list {{#PARTITION_HW_RESOURCE}}{{HW_RESOURCE}} {{/PARTITION_HW_RESOURCE}}]
rmGroup::setResetAfterReconfig ${{PARTITION_ID}} {{PARTITION_RESET_AFTER_RECONFIG}}
rmGroup::setSnappingMode ${{PARTITION_ID}} {{PARTITION_SNAPPING_MODE}}

{{/RECONFIG_PARTITION}}

###############################################################
### Reconfig Modules
###############################################################

{{#RECONFIG_MODULE}}# Create reconfig module
set {{FIXED_FILES_ID}} [fileGroup::create]
{{#RECONFIG_MODULE_FILE}}fileGroup::add ${{FIXED_FILES_ID}} {{RECONFIG_MODULE_FILE_DIR}} {{RECONFIG_MODULE_FILE_NAME}}
{{/RECONFIG_MODULE_FILE}}
rmGroup::addNewModule ${{RECONFIG_MODULE_PARTITION_ID}} "{{RECONFIG_MODULE_NAME}}" ${{FIXED_FILES_ID}}


{{/RECONFIG_MODULE}}

###############################################################


###############################################################
### Configurations
###############################################################
{{#CONFIGURATION}}# Create configuration
set {{CONFIG_ID}} [cfgGroup::create "{{CONFIG_NAME}}"]
{{#CONFIGURATION_ADD_MODULE}}cfgGroup::addNewModule ${{CONFIG_ID}} ${{CONFIG_PARTITION_ID}} "{{CONFIG_RECONFIG_MODULE_NAME}}" "implement"
{{/CONFIGURATION_ADD_MODULE}}
cfgGroup::setBitstreamCompress ${{CONFIG_ID}} {{CONFIG_BITSTREAM_COMPRESS}}

{{/CONFIGURATION}}
###############################################################


###############################################################
### Reference & Blanking Configurations
###############################################################
set createBlanking {{CREATE_BLANKING_VALUE}}
set compressBlanking {{COMPRESS_BLANKING_VALUE}}

set compressReference {{COMPRESS_REFERENCE_VALUE}}
###############################################################
