# File generated by dynDeT

### Connect to Cortex processor
connect arm hw

source {{WRAPPER_HW_PLATFORM_SOURCE}}
ps7_init
ps7_post_config

### Download factory bitstreams
{{#DOW_FACTORY_BITSTREAM}}dow -data {{BITSTREAMS_DIR}}{{FACTORY_BITSTREAM}} {{MEM_ADDR}}
{{/DOW_FACTORY_BITSTREAM}}

### Download apps
{{#DOW_APP}}dow {{APP}}
run
{{/DOW_APP}}

